
  /user :
    get :
      summary: Get User Profile
      tags: [UserAuthentication]
      description:  Get User Profile
      security:      
            - authorization: []    
      responses:
          200:
            description: success
            content : 
              application/json : 
                schema : 
                  $ref :  '#/components/responses/schemas/200getContent'
                examples : 
                  user : 
                    $ref : '#/components/examples/userProfile'
          403:
           $ref: '#/components/definitions/403'
          404: 
            description: not found
            content : 
              application/json : 
                schema  : 
                  $ref  :   '#/components/responses/schemas/404notFound'
                example : 
                  messasge : پروفایل کاربری یافت نشد
          500:
            $ref: '#/components/definitions/500'
    patch:
        summary: Update Profile
        tags: [UserAuthentication]
        description: Update Profile
        security:
          - authorization: []
        requestBody:
          content:
            multipart/form-data:
              schema:
                $ref : '#/components/schemas/updateProfile'
        responses:
          200:
            $ref: '#/components/definitions/200updatedContent'
          400:
            description: bad request
            content : 
              application/json : 
                schema :  
                  $ref : '#/components/responses/schemas/400badRequest' 
                example : 
                  message : ' "نام" بیشتر از حد مجاز  است (حداکثر 15 کاراکتر) " || "نام" کوتاه تر از حد مجاز است (حداقل 2 کاراکتر)'
          401: 
            $ref: '#/components/definitions/401'
          403:
            $ref: '#/components/definitions/403'
          500:
            $ref: '#/components/definitions/500'
    delete:
      summary: Delete A User 
      tags:  [UserAuthentication]
      description: Delete A User (Required Permoision)
      security:
        - authorization: []
      parameters: 
        - name : userID
          in : query
          description : The ID Of The User
      responses:
        200:
          description: success
          content : 
            application/json : 
              schema : 
                $ref : '#/components/responses/schemas/200removeContent'
              example : 
                status : success
                message : کاربر با موفقیت حذف شد 
        400:
          description: bad request
          content : 
            application/json : 
              schema :  
                $ref : '#/components/responses/schemas/400badRequest' 
              example :
                message : شناسه کاربر صحیح نمیباشد 
        404: 
          $ref: '#/components/definitions/404'
        401: 
          $ref: '#/components/definitions/401'
        500:
          description: internal server error   
          content :   
            application/json : 
              schema : 
                $ref : '#/components/responses/schemas/500InternalServerError'
              examples :
                internalServerError :  
                  $ref : '#/components/examples/internalServerError'
                removeFailed :  
                    $ref : '#/components/examples/removeFailed'
  /user/list :
     get :
      summary: Get List Of Users 
      tags: [UserAuthentication]
      description:  Get List Of Users 
      security:      
            - authorization: []    
      parameters: 
          - name : search
            in : query
            description : search specific content
            schema:
              type: string
      responses:
          200:
            description: success
            content : 
              application/json : 
                schema : 
                  $ref :  '#/components/responses/schemas/200getContent'
                examples : 
                  users : 
                    $ref : '#/components/examples/users'
                  contentNull : 
                    $ref: '#/components/examples/contentNull'
          403:
            $ref: '#/components/definitions/403'
          500:
           $ref: '#/components/definitions/500'

  