
  /admin/courses/chapters/{chapterId} :
     get :
      summary: Get A chapter Of Course
      tags: ['Admin Panel [Chapters]']
      description: Get A chapter Of Course
      security:
            - authorization: []    
      parameters: 
          - name : chapterId
            in : path
            description : the id of chapter      
            required : true
            schema:
              type: string
              pattern: "^[a-f\\d]{24}$"
      responses:
          200:  
            description: success
            content : 
              application/json : 
                schema : 
                  $ref :  '#/components/responses/schemas/200getContents'
                examples : 
                  chapter : 
                    $ref : '#/components/examples/chapter'
                  contentNull : 
                    $ref : '#/components/examples/contentNull'
          500:
            $ref: '#/components/definitions/500'
          403:
            $ref: '#/components/definitions/403'
  /admin/courses/chapters:
    post:
      summary: Create a Chapter
      tags: ['Admin Panel [Chapters]']
      description: Create a Specifiec Chapter
      security:
        - authorization: []
      consumes : 
        - application/x-www-form-urlencoded
        - application/json
      requestBody:
        content:
          application/json:
            schema:
              $ref : '#/components/schemas/chapter'
      responses:
        201:
          description: success
          content : 
            application/json : 
              schema : 
                $ref : '#/components/responses/schemas/201createdContent'
              example : {
                "status": "success",
                "message": "",
                "data": {
                  "title": "فصل اول - مقدماتی",
                  "description": "فصل اول - مقدماتی فصل اول - مقدماتی فصل اول - مقدماتی فصل اول - مقدماتی",
                  "courseId": "64f9d19559f0e8b27fe7eba6",
                  "episods": [],
                  "_id": "64fde2ad7bb3e957388a0ab2",
                  "__v": 0 ,
                }
              }
        400:
          description: bad request
          content : 
            application/json :
              schema : 
                $ref : '#/components/responses/schemas/400badRequest'
              example :
                message : ' "توضیحات" نمیتواند خالی باشد || "عنوان" کوتاه تر از حد مجاز است (حداقل 3 کاراکتر)'
        401:
          $ref: '#/components/definitions/401'
        403:
          $ref: '#/components/definitions/403'
        500:
          $ref: '#/components/definitions/500'
    patch:
      summary: Update A Specific Chapter
      tags: ['Admin Panel [Chapters]']
      description:  Update A Specific Chapter
      security:
        - authorization: []
      requestBody:
        content:
          application/json:
            schema:
              $ref : '#/components/schemas/chapter'
      responses:
        200:
          description: success
          content :  
            application/json : 
              schema : 
                $ref : '#/components/responses/schemas/200updatedContent'
              example :
                status : success 
                message : بروز رسانی با موفقیت انجام شد
        400:
          description: bad request
          content : 
            application/json : 
              schema :  
                $ref : '#/components/responses/schemas/400badRequest' 
              example : 
                message : ' "توضیحات" نمیتواند خالی باشد || "عنوان" کوتاه تر از حد مجاز است (حداقل 3 کاراکتر)'
        404:
          description: not found
          content : 
            application/json : 
              schema  : 
                $ref  :   '#/components/responses/schemas/404notFound'
              example : 
                messasge : فصل مورد نظر یافت نشد
        401: 
          $ref: '#/components/definitions/401'
        403: 
          $ref: '#/components/definitions/403'
        500:
          $ref: '#/components/definitions/500'
    delete:
      summary: Delete A Chapter
      tags:  ['Admin Panel [Chapters]']
      description: Delete A Specifiec Chapter
      security:
        - authorization: []
      requestBody:
          content:
            application/json:
              schema:
                type : object 
                properties : 
                  chapterId: 
                    type : string  
                    pattern : "^[a-f\\d]{24}$"
                    description: The Id Of The Chapter 
                    required : true
      responses:
        200:
          description: success
          content : 
            application/json : 
              schema : 
                $ref : '#/components/responses/schemas/200removeContent'
              example : 
                status : success
                message : فصل با موفقیت حذف شد 
        400:
          description: bad request
          content : 
            application/json : 
              schema :  
                $ref : '#/components/responses/schemas/400badRequest' 
              example :
                message : شناسه فصل صحیح نمیباشد 
        404: 
          description: not found
          content : 
            application/json : 
              schema  : 
                $ref  :   '#/components/responses/schemas/404notFound'
              example : 
                messasge : فصل مورد نظر یافت نشد
        401: 
          $ref: '#/components/definitions/401'
        403: 
          $ref: '#/components/definitions/403'
        500:
          description: internal server error   
          content : 
            application/json : 
              schema : 
                $ref : '#/components/responses/schemas/500InternalServerError'
              examples :
                internalServerError :  
                  $ref : '#/components/examples/internalServerError'
                removeFailed :  
                    $ref : '#/components/examples/removeFailed'
  