
  /admin/products/{productId} :
    get : 
      summary: Get A Specific Product
      tags: ['Admin Panel [Products]']
      description: Get A Specific Product
      security:
        - authorization: []    
      parameters: 
        - name : productId
          in : path
          description : the id of product
          required : true
          schema:
            type: string
            pattern: "^[a-f\\d]{24}$"
      responses:
        200:
          description: success 
          content : 
            application/json : 
              schema : 
                $ref : '#/components/responses/schemas/200getContents'
              example : 
                status : 'success'
                count : 1
                data :  {
                  "_id": "64f1c89380afcfb0059964b9",
                  "title": "محصول  نمونه",
                  "summary": "توضیحات محصول نمونه",
                  "description": "توضیحات کاملتر محصول نمونه",
                  "imageCover": "http://localhost:8080/uploads/products/2023/7/3/sampleImage1693410882758.jpg",
                  "images": [
                    "http://localhost:8080/uploads/products/2023/7/3/sample1693410882757.jpg",
                    "http://localhost:8080/uploads/products/2023/7/3/sample1693410882758.jpg",
                  ],
                  "tags": [
                    "#sampleTag1",
                    "#sampleTag2",
                  ],
                  "category": {
                    "name": "javaScript",
                  },
                  "comments": [],
                  "likes": [],
                  "disLikes": [],
                  "bookmarks": [],
                  "price": 1000,
                  "discount": "20",
                  "type": "virtual",
                  "suplier": "63dd98711035750bf64d3a94",
                  "properties": {
                    "length": 100,
                    "height": 12,
                    "width": 13,
                    "weight": 14,
                    "colors": "blue",
                    "model": "m234",
                    "madein": "iran",
                  }
                }
        400:
          description: bad request
          content : 
            application/json : 
              schema :  
                $ref : '#/components/responses/schemas/400badRequest' 
              example :
                message : شناسه محصول صحیح نمیباشد 
        404: 
          description: not found
          content : 
            application/json : 
              schema  : 
                $ref  :   '#/components/responses/schemas/404notFound'
              example : 
                messasge : محصول مورد نظر یافت نشد
        500:
          description: internal server error   
          content : 
            application/json : 
              schema : 
                $ref : '#/components/responses/schemas/500InternalServerError'
              example : 
                message : خطای داخلی سرور 
  /admin/products:
    get:
      summary: Get List Of Products
      tags: ['Admin Panel [Products]']
      description: Get List Of All Products
      security:
        - authorization: []    
      parameters: 
        - name : search
          in : query
          description : search box
          schema:
            type: string
      responses:
        200:
          description: success
          content : 
            application/json : 
              schema : 
                $ref :  '#/components/responses/schemas/200getContents'
              examples : 
                product : 
                  $ref : '#/components/examples/product'
                contentNull : 
                  $ref : '#/components/examples/contentNull'
        500:
          description: internal server error
          content : 
            application/json : 
              schema : 
                $ref: '#/components/responses/schemas/500InternalServerError'
              example : 
                message : 'خطای داخلی سرور'
    post:
      summary: Create a Product
      tags: ['Admin Panel [Products]']
      description: Create a Specifiec Blog
      security:
        - authorization: []
      consumes : 
        - application/x-www-form-urlencoded
        - application/json
      requestBody:
         content:
          multipart/form-data:
            schema:
              type : object 
              properties : 
                title: 
                  type : string  
                  required : true
                  description: The Title Of The Product 
                summary: 
                  type : string  
                  required : true
                  description: The Summary Of The Product 
                description: 
                  type : string  
                  required : true
                  description: The Description Of The Product 
                tags: 
                  type : array
                  items : 
                    type : string
                    example : '#'
                  description: The Tags Of The Product 
                category: 
                 type : string
                 pattern : "^[a-f\\d]{24}$"
                 required : true
                 description: The Category Of The Product 
                type: 
                 type : string
                 enum : ['virtual' ,'phicycal' ]  
                 required : true
                 description: The Summary Of The Product 
                price : 
                  type : number 
                  required : true
                  description : The Price Of The Product
                discount : 
                  type : number 
                  description : The Discount Of The Product
                images :
                  type : array
                  items : 
                    type : file
                    format : binary
                  description: The Images Of The Product
                imageCover :
                  type : file
                  description: The Image Cover Of The Product
                properties : 
                  type : object
                  properties :
                    length : 
                      type : number
                      defualt : 0
                    height : 
                      type : number
                      defualt : 0
                    width : 
                      type : number
                      defualt : 0
                    weight : 
                      type : number
                      defualt : 0
                    colors : 
                      type : string
                      example : 0
                    model : 
                      type : number
                      defualt : 0
                    madein : 
                      type : number
                      defualt : 0
            encoding :
              tags : 
                 contentType: application/json
              properties : 
                 contentType: application/json
      responses:
        201:
          description: success
          content : 
            application/json : 
              schema : 
                $ref : '#/components/responses/schemas/201createdContent'
              example :
                status : 'success'
                data :  {
                  "_id": "64f1c89380afcfb0059964b9",
                  "title": "محصول  نمونه",
                  "summary": "توضیحات محصول نمونه",
                  "description": "توضیحات کاملتر محصول نمونه",
                  "imageCover": "http://localhost:8080/uploads/products/2023/7/3/sampleImage1693410882758.jpg",
                  "images": [
                    "http://localhost:8080/uploads/products/2023/7/3/sample1693410882757.jpg",
                    "http://localhost:8080/uploads/products/2023/7/3/sample1693410882758.jpg",
                  ],
                  "tags": [
                    "#sampleTag1",
                    "#sampleTag2",
                  ],
                  "category": {
                    "name": "javaScript",
                  },
                  "comments": [],
                  "likes": [],
                  "disLikes": [],
                  "bookmarks": [],
                  "price": 1000,
                  "discount": "20",
                  "type": "virtual",
                  "suplier": "63dd98711035750bf64d3a94",
                  "properties": {
                    "length": 100,
                    "height": 12,
                    "width": 13,
                    "weight": 14,
                    "colors": "blue",
                    "model": "m234",
                    "madein": "iran",
                  }
                }
        400:
          description: bad request
          content : 
            application/json :
              schema : 
                $ref : '#/components/responses/schemas/400badRequest'
              examples :
                incorrectRequirements:
                  $ref :  '#/components/examples/incorrectRequirements'
                incorrectImageFormat:
                  $ref :  '#/components/examples/incorrectImageFormat'
                fileTooLarge:
                  $ref :  '#/components/examples/fileTooLarge'
        401:
          description: unauthorized
          content : 
            application/json :
              schema : 
                $ref : '#/components/responses/schemas/401unuthorized'
              example: 
                message : 'وارد حساب کاربری خود شوید'
        500:
          description: internal server error , 
          content : 
            application/json : 
              schema : 
                $ref : '#/components/responses/schemas/500InternalServerError'
              example : 
                message : 'خطای داخلی سرور'
    patch:
      summary: Update A Specific Product
      tags: ['Admin Panel [Products]']
      description:  Update A Specific Product
      security:
        - authorization: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type : object 
              properties : 
                productId: 
                  type : string  
                  required : true
                  pattern: "^[a-f\\d]{24}$"
                  description: The Id Of The Product 
                title: 
                  type : string  
                  required : true
                  description: The Title Of The Product 
                summary: 
                  type : string  
                  required : true
                  description: The Summary Of The Product 
                description: 
                  type : string  
                  required : true
                  description: The Description Of The Product 
                tags: 
                  type : array
                  items : 
                    type : string
                    example : '#'
                  description: The Tags Of The Product 
                category: 
                 type : string
                 pattern : "^[a-f\\d]{24}$"
                 required : true
                 description: The Category Of The Product 
                type: 
                 type : string
                 enum : ['virtual' , 'phicycal']  
                 required : true
                 description: The Summary Of The Product 
                price : 
                  type : number 
                  required : true
                  description : The Price Of The Product
                discount : 
                  type : number 
                  description : The Discount Of The Product
                images :
                  type : array
                  items : 
                      type : string
                      format : binary
                  description: The Images Of The Product
                imageCover :
                  type : file
                  description: The Image Cover Of The Product
                properties : 
                  type : object
                  properties :
                    length : 
                      type : number
                      defualt : 0
                    height : 
                      type : number
                      defualt : 0
                    width : 
                      type : number
                      defualt : 0
                    weight : 
                      type : number
                      defualt : 0
                    colors : 
                      type : number
                      defualt : 0
                    model : 
                      type : number
                      defualt : 0
                    madein : 
                      type : number
                      defualt : 0
            encoding :
              tags: 
                 contentType: application/json
              productId : 
                 contentType: application/json
              properties : 
                 contentType: application/json
      responses:
        200:
          description: success
          content :  
            application/json : 
              schema : 
                $ref : '#/components/responses/schemas/200updatedContent'
              example :
                status : success 
                message : بروز رسانی با موفقیت انجام شد
        400:
          description: bad request
          content : 
            application/json : 
              schema :  
                $ref : '#/components/responses/schemas/400badRequest' 
              examples : 
                incorrectRequirements:
                  $ref :  '#/components/examples/incorrectRequirements'
                incorrectImageFormat:
                  $ref :  '#/components/examples/incorrectImageFormat'
                fileTooLarge:
                  $ref :  '#/components/examples/fileTooLarge'     
        404:
          description: not found
          content : 
            application/json : 
              schema  : 
                $ref  :   '#/components/responses/schemas/404notFound'
              example : 
                messasge : محصول مورد نظر یافت نشد
        401: 
          description: unauthorized 
          content : 
            application/json : 
              schema : 
                $ref : '#/components/responses/schemas/401unuthorized'
              example : 
                message : وارد حساب کاربری خود شوید
        500:
          description: internal server error   
          content : 
            application/json : 
              schema : 
                $ref : '#/components/responses/schemas/500InternalServerError'
              example : 
                message : خطای داخلی سرور 
    delete:
      summary: Delete A Product
      tags:  ['Admin Panel [Products]']
      description: Delete A Specifiec Product
      security:
        - authorization: []
      requestBody:
         content:
          application/json:
            schema:
              type : object 
              properties : 
                productId: 
                  type : string  
                  pattern : "^[a-f\\d]{24}$"
                  description: The Id Of The product 
                  required : true
      responses:
        200:
          description: success
          content : 
            application/json : 
              schema : 
                $ref : '#/components/responses/schemas/200removeContent'
              example : 
                message : محصول با موفقیت حذف شد 
        400:
          description: bad request
          content : 
            application/json : 
              schema :  
                $ref : '#/components/responses/schemas/400badRequest' 
              example :
                message : شناسه محصول صحیح نمیباشد 
        404: 
          description: not found
          content : 
            application/json : 
              schema  : 
                $ref  :   '#/components/responses/schemas/404notFound'
              example : 
                messasge : محصول مورد نظر یافت نشد
        401: 
          description: unauthorized 
          content : 
            application/json : 
              schema : 
                $ref : '#/components/responses/schemas/401unuthorized'
              example : 
                message : وارد حساب کاربری خود شوید
        500:
          description: internal server error   
          content : 
            application/json : 
              schema : 
                $ref : '#/components/responses/schemas/500InternalServerError'
              examples :
                internalServerError :  
                  $ref : '#/components/examples/internalServerError'
                removeFailed :  
                   $ref : '#/components/examples/removeFailed'
