tags:
  - name : IndexPage
  - name : Authentication
  - name : RBAC Panel [Admin]
    description : (Required Super-admin Or Master Permission)
  - name : Admin Panel [Blogs]
  - name : Admin Panel [Products]
  - name : Admin Panel [Categories]
  - name : Admin Panel [Courses]
  - name : Admin Panel [Chapters]
  - name : Admin Panel [Episodes]
  - name : Developers Routes    