tags:
  - name : IndexPage
  - name : UserAuthentication
  - name : RBAC Panel [Admin]
    description : (Required Permission)
  - name : Admin Panel [Blogs]
    description : (Required Permission)
  - name : Admin Panel [Products]
    description : (Required Permission)
  - name : Admin Panel [Categories]
    description : (Required Permission)
  - name : Admin Panel [Courses]
    description : (Required Permission)
  - name : Admin Panel [Chapters]
    description : (Required Permission)
  - name : Admin Panel [Episodes]
    description : (Required Permission)
  - name : Developers Routes    