{
  blogs {
    _id
    title
    summary
    body
    image
    likes {
      _id
      firstName
    }
    comments {
      _id
      comment
      answer {
        user {
          _id
          firstName
          lastName
        }
        _id
        answer
      }
      user {
        _id
        firstName
        lastName
      }
    }
    category {
      _id
      name
    }
    author {
      _id
      firstName
      lastName
    }
  } 
  
}
