{
  courses{
    _id
    title
    category{
      name
      subCategory 
    }
    comments{
      comment
      user {
        firstName
        lastName
      }
    }
    chapters{
    	duration
      courseId
      title
      episodes {
        address
        title
        description
      }
    }
  }
}
